# Generated by Django 4.0.5 on 2024-12-19 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculos',
            options={'permissions': [('add_vehiculo', 'Puede agregar vehículos'), ('view_vehiculo', 'Puede ver vehículos'), ('delete_vehiculo', 'Puede eliminar vehículos'), ('update_vehiculo', 'Puede actualizar vehículos')]},
        ),
    ]
